/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javax.swing.*;
import java.awt.*;

public class App {
    public static void main(String[] args) {
    	JFrame f = new JFrame("App");
    	f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    	f.setLayout(new FlowLayout());
    	JLabel l = new JLabel("Hello World");
    	l.setFont(new Font("Arial", Font.BOLD, 50));
    	f.add(l);
    	f.setSize(512,256);
    	f.setVisible(true);
    	f.setLocationRelativeTo(null);
    }
}
